#!/usr/bin/env bash
# Bash script to configure Nginx redirection

# Backup the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Use sed to replace the root location block with a redirection configuration
sed -i '/^.*location \/ {$/ {
N; s/location \/ {\n[[:space:]]*# First attempt to serve request as file, then/\
&\n    location \/redirect_me {\
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\
    }/}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

