#!/usr/bin/env bash
# Bash script to configure Nginx custom 404 page

# Backup the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Use sed to add a custom error page for 404 errors
sed -i '/^.*server_name localhost;$/a\\n    error_page 404 /404.html;\n    location = /404.html {\n        root /usr/share/nginx/html;\n        internal;\n        echo "Ceci n'\''est pas une page";\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

